language: cpp
dist: bionic
sudo: required

addons:
  apt:
    update: true
    packages:
      - libopencv-dev
os:
  - linux

compiler:
  - gcc
  - clang

branches:
  only:
    - master

script:
  - mkdir build
  - cd build
  - cmake -DCPACK_GENERATOR=DEB ..
  - make package -j

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "build/HandMouse-*.deb"
    - "build/HandMouse-*.tar.gz"
  overwrite: true
  skip_cleanup: true
  on:
    - condition: "$CC = gcc"
