language: cpp
dist: bionic
sudo: required

addons:
  apt:
    update: true
    packages:
      - libopencv-dev
os:
  - linux

compiler:
  - gcc
  - clang

branches:
  only:
    - master

script:
  - mkdir build
  - cd build
  - cmake -DCPACK_GENERATOR=DEB ..
  - make package -j
