language: cpp
dist: focal
sudo: required

addons:
  apt:
    update: true
    packages:
      - libopencv-dev
      - libboost-all-dev
      - python3-numpy
os:
  - linux

compiler:
  - gcc
  - clang

branches:
  only:
    - master

script:
  - mkdir build
  - cd build
  - cmake -DCPACK_GENERATOR=DEB ..
  - make package -j

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - HandMouse-*.deb
    - HandMouse-*.tar.gz
    - python/HandMouse_py.so
  overwrite: true
  skip_cleanup: true
  on:
    branch: master
    condition: "$CC = gcc"
